Fix Husky / Pre-commit and MUI Dates version🔥

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,15 +6,15 @@ echo '🏗️👷 Styling, testing and building your project before committing'
 # Applying Lint
 yarn lint ||
 (
-    echo '🟦🟦🟦🟦 You have to fix some things 🟦🟦🟦🟦 
+    echo '🟦🟦🟦🟦 You have to fix some things 🟦🟦🟦🟦
             Make the required changes listed above, add changes and try to commit again.';
     false;
 )
 
 # Check Prettier standards
-yarn check-format ||
+yarn format ||
 (
-    echo '🐍🐍🐍🐍 Your styling looks bad! 🐍🐍🐍🐍 
+    echo '🐍🐍🐍🐍 Your styling looks bad! 🐍🐍🐍🐍
             Prettier Check Failed. Run yarn format, add changes and try commit again.';
     false;
 )
@@ -22,9 +22,9 @@ yarn check-format ||
 # Check ESLint Standards
 yarn check-lint ||
 (
-        echo '🔴🔴🔴🔴 ESLint fail! 🔴🔴🔴🔴 
+        echo '🔴🔴🔴🔴 ESLint fail! 🔴🔴🔴🔴
                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-        false; 
+        false;
 )
 
 # Check tsconfig standards
@@ -48,12 +48,11 @@ echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build no
 yarn build ||
 (
     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
-            Next build failed: View the errors above to see why. 
+            Next build failed: View the errors above to see why.
     '
     false;
 )
 
 # If everything passes... Now we can commit
 echo '🚀🚀🚀🚀 You win this time... I am committing this now. 🚀🚀🚀🚀'
-
 
